Project2-BuellerWebSln/Bueller.MVC/Models/Grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Bueller.MVC.Models
{
    public class Grade
    {

        [ScaffoldColumn(false)]
        public int GradeId { get; set; }

        [Required(ErrorMessage = "Evaluation type is required")]
        [DataType(DataType.Text)]
        [StringLength(50, ErrorMessage = "Evaluation type cannot be more than 50 characters")]
        [Display(Name = "Evaluation Type")]
        public string EvaluationType { get; set; }

        [Required(ErrorMessage = "Score is required")]
        [Range(0, 200, ErrorMessage = "Score must be between 0 and 200")]
        public double Score { get; set; }

        [Required(ErrorMessage = "Grade letter is required")]
        [DataType(DataType.Text)]
        [StringLength(2, ErrorMessage = "Grade letter cannot be more than 2 characters")]
        [Display(Name = "Letter Grade")]
        public string GradeLetter { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(500, ErrorMessage = "Comment cannot be more than 500 characters")]
        public string Comment { get; set; }

        [Required]
        [ScaffoldColumn(false)]
        public int FileId { get; set; }
        [ForeignKey("FileId")]
        public virtual File File { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime Modified { get; set; }
    }
}

Project2-BuellerWebSln/Bueller.MVC/Controllers/GradeController.cs
using Bueller.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Bueller.MVC.Controllers
{
    public class GradeController : AServiceController
    {
        // GET: Grade
        public ActionResult Create(int fileId)
        {
            if (Request.Cookies.Get("Role").Value != "teacher")
            {
                return View("Error");
            }

            Grade grade = new Grade();
            grade.FileId = fileId;


            return View(grade);
        }

        public ActionResult Index()
        {
      


            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(Grade newGrade)
        {
            if (Request.Cookies.Get("Role").Value != "teacher")
            {
                return View("Error");
            }


            if (!ModelState.IsValid)
            {
                return View("Error");
            }


            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Post, $"api/Grade/Add");
            apiRequest.Content = new ObjectContent<Grade>(newGrade, new JsonMediaTypeFormatter());

            HttpResponseMessage apiResponse;


            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }



            return RedirectToAction("MyClasses","Class");
        }
    }
}

Project2-BuellerWebSln/Bueller.MVC/Views/Grade/Create.cshtml
@model Bueller.MVC.Models.Grade


<h2>Add Grade</h2>
@using (Html.BeginForm("Create", "Grade", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.FileId)

            @Html.LabelFor(model => model.GradeLetter, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(m => m.GradeLetter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GradeLetter, "", new { @class = "text-danger" })
            <br />
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(m => m.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })

            <br />
            @Html.LabelFor(model => model.EvaluationType, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(m => m.EvaluationType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EvaluationType, "", new { @class = "text-danger" })

            <br />
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(m => m.Score, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Grade" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project2-BuellerWebSln/Bueller.MVC/Views/Grade/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}