Project2-BuellerWebSln/Bueller.MVC/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bueller.MVC.Models;

namespace Bueller.MVC.Controllers
{
    public class ClassController : AServiceController
    {
        //add instructor name to view for students? or withhold if teacher logged in...
        //add enrollment count too?
        //have create/edit/delete only show up for teachers
        //details view for description and link to textbook purchase? subject and class level?

        // GET: Classes
        [HttpGet]
        public async Task<ViewResult> Index()
        {

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, "api/Class/GetAll");
            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var classes = await apiResponse.Content.ReadAsAsync<List<Class>>();

            ViewBag.Role = Request.Cookies["Role"].Value;
            return View(classes);
        }


        [HttpGet]
        public async Task<ViewResult> MyClasses()
        {

            var id = Request.Cookies["Id"].Value;
            var role = Request.Cookies["Role"].Value;

            HttpRequestMessage apiRequest;

            if (role == "student")
                apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetByStudentId/{id}");
            else if (role == "teacher")
                apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetByTeacherId/{id}/");
            else
                apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetAll");

            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            List<Class> classes = new List<Class>();
            if (apiResponse.IsSuccessStatusCode)
            {
                classes = await apiResponse.Content.ReadAsAsync<List<Class>>();
            }


            ViewBag.Role = Request.Cookies["Role"].Value;
            return View(classes);
        }

        // GET: Classes
        [HttpGet]
        public async Task<ViewResult> Details(int id)
        {
            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetById/{id}");

            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var classresponse = await apiResponse.Content.ReadAsAsync<Class>();

            HttpRequestMessage apiRequest2 = CreateRequestToService(HttpMethod.Get, $"api/Class/EnrollmentCount/{id}");
            HttpResponseMessage apiResponse2;

            try
            {
                apiResponse2 = await HttpClient.SendAsync(apiRequest2);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse2.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var count = await apiResponse2.Content.ReadAsAsync<int>();
            classresponse.EnrollmentCount = count;

            return View(classresponse);
        }

        // GET: Classes
        [HttpGet]
        public async Task<ActionResult> EnrollConfirm(int id)
        {
            if (Request.Cookies.Get("Role").Value != "student")
            {
                return View("Error");
            }

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetById/{id}");

            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var classresponse = await apiResponse.Content.ReadAsAsync<Class>();

            ViewBag.Id = id;
            return View(classresponse);
            //return RedirectToAction("Index");
        }

        // GET: Enroll
        [HttpGet]
        public async Task<ActionResult> Enroll(int id)
        {
            if (Request.Cookies.Get("Role").Value != "student")
            {
                return View("Error");
            }

            var studentid = Convert.ToInt32(Request.Cookies.Get("Id").Value);
            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/Enroll/{id}/{studentid}");

            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var classresponse = await apiResponse.Content.ReadAsAsync<Class>();

            //return View(classresponse);
            return RedirectToAction("MyClasses");
        }


        public async Task<ActionResult> Create()
        {
            //Assignment assignment = new Assignment();
            //assignment.ClassId = ClassId;

            if (Request.Cookies.Get("Role").Value != "teacher")
            {
                return View("Error");
            }

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, "api/Class/Subject/GetAllNames");
            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var subjects = await apiResponse.Content.ReadAsAsync<List<string>>();
            var subjects2 = subjects.OrderBy(q => q);
            var subjectselectlist = subjects2.Select(c => new SelectListItem { Text = c, Value = c }).ToList();

            ViewBag.Subjects = subjectselectlist;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Class newClass)
        {
            if (Request.Cookies.Get("Role").Value != "teacher")
            {
                return View("Error");
            }
            HttpRequestMessage apiRequest2 = CreateRequestToService(HttpMethod.Get, $"api/Class/Subject/GetByName/{newClass.SubjectName}");
            HttpResponseMessage apiResponse2;

            try
            {
                apiResponse2 = await HttpClient.SendAsync(apiRequest2);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse2.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var subject = await apiResponse2.Content.ReadAsAsync<Subject>();

            newClass.SubjectId = subject.SubjectId;
            newClass.TeacherId = Convert.ToInt32(Request.Cookies.Get("Id").Value);


            if (!ModelState.IsValid)
            {
                return View("Error");
            }


            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Post, $"api/Class/Add");
            apiRequest.Content = new ObjectContent<Class>(newClass, new JsonMediaTypeFormatter());

            HttpResponseMessage apiResponse;


            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }



            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return View("Error");
            }

            if (Request.Cookies["Role"].Value != "teacher")
            {
                return View("Error");
            }

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Class/GetById/{id}");
            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            Class classresult = new Class();
            if (apiResponse.IsSuccessStatusCode)
            {
                classresult = await apiResponse.Content.ReadAsAsync<Class>();
            }

            if (classresult.TeacherId != Convert.ToInt32(Request.Cookies["Id"].Value))
            {
                return View("Error");
            }

            HttpRequestMessage apiRequest2 = CreateRequestToService(HttpMethod.Get, "api/Class/Subject/GetAllNames");
            HttpResponseMessage apiResponse2;

            try
            {
                apiResponse2 = await HttpClient.SendAsync(apiRequest2);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse2.IsSuccessStatusCode)
            {

Project2-BuellerWebSln/Bueller.MVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bueller.MVC.Models;

namespace Bueller.MVC.Controllers
{
    public class StudentController : AServiceController
    {
        // GET: Student
        [HttpGet]
        public async Task<ActionResult> Index(int ClassId)
        {
            if (ClassId == 0)
            {
                return View("Error");
            }

            HttpRequestMessage apiRequest =
                CreateRequestToService(HttpMethod.Get, $"api/Assignment/GetByClassId/{ClassId}");

            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            if (!apiResponse.IsSuccessStatusCode)
            {
                return View("Error");
            }

            var assignment = await apiResponse.Content.ReadAsAsync<Assignment>();

            return View(assignment);
        }

        public async Task<ActionResult> GetTeachers()
        {
            int id = Convert.ToInt32(Request.Cookies["Id"].Value);

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Student/GetTeachersByStudentId/{id}");
            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            List<Employee> files = new List<Employee>();
            if (apiResponse.IsSuccessStatusCode)
            {
                files = await apiResponse.Content.ReadAsAsync<List<Employee>>();
            }


            return View(files);
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project2-BuellerWebSln/Bueller.MVC/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bueller.MVC.Models;

namespace Bueller.MVC.Controllers
{
    public class TeacherController : AServiceController
    {
        // GET: Teacher
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetStudents()
        {
            int id = Convert.ToInt32(Request.Cookies["Id"].Value);

            HttpRequestMessage apiRequest = CreateRequestToService(HttpMethod.Get, $"api/Employee/GetStudentsByTeacherId/{id}");
            HttpResponseMessage apiResponse;

            try
            {
                apiResponse = await HttpClient.SendAsync(apiRequest);
            }
            catch
            {
                return View("Error");
            }

            List<Student> files = new List<Student>();
            if (apiResponse.IsSuccessStatusCode)
            {
                files = await apiResponse.Content.ReadAsAsync<List<Student>>();
            }


            return View(files);
        }
    }
}

Project2-BuellerWebSln/Bueller.MVC/Views/Shared/EmployeeView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Bueller", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            @*<ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>*@
            <ul class="nav navbar-nav navbar-right">
                <li style="padding: 15px; color: white">@Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)</li>
                <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Bueller | @Html.ActionLink("About", "About", "Home") | @Html.ActionLink("Contact", "Contact", "Home")</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

Project2-BuellerWebSln/Bueller.MVC/Views/Shared/HomeView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bueller</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="~/css/clean-blog.min.css" rel="stylesheet">
</head>
<body style="background-color: lightgrey">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="@Url.Action("Index","Home")">Bueller</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Register","Account")">Register<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login", "Account")">Login<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <div style="height: 60px"></div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bueller | @Html.ActionLink("About", "About", "Home") | @Html.ActionLink("Contact", "Contact", "Home")</p>
        </footer>
    </div>

    @Scripts.Render("~/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/vendor/bootstrap/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/js/clean-blog.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

Project2-BuellerWebSln/Bueller.MVC/Views/Shared/StudentView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - Bueller</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="~/css/clean-blog.min.css" rel="stylesheet">
</head>
<body style="background-color: lightgrey">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">Bueller</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("MyClasses","Class")">My Classes<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Class")">All Classes<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("GetTeachers", "Student")">My Teachers<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Profile")">Profile</a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Logout","Account")">Logout</a>
                    </li>
                    <li style="padding-top: 7.5px; color: white">
                        @Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)
                        @*<a class="nav-link disabled"> @Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)</a>*@
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="height: 60px"></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bueller | @Html.ActionLink("About", "About", "Home") | @Html.ActionLink("Contact", "Contact", "Home")</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Project2-BuellerWebSln/Bueller.MVC/Views/Shared/TeacherView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - Bueller</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="~/css/clean-blog.min.css" rel="stylesheet">
</head>
<body style="background-color: lightgrey">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">Bueller</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("MyClasses","Class")">My Classes<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Class")">All Classes<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("GetStudents", "Teacher")">My Students<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Profile")">Profile</a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Logout","Account")">Logout</a>
                    </li>
                    <li style="padding-top: 7.5px; color: white">
                        @Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)
                        @*<a class="nav-link disabled">@Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)</a>*@
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="height: 60px"></div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bueller | @Html.ActionLink("About", "About", "Home") | @Html.ActionLink("Contact", "Contact", "Home")</p>
        </footer>
    </div>

    @Scripts.Render("~/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/vendor/bootstrap/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/js/clean-blog.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>





@*<div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Bueller", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("My Classes", "MyClasses", "Class")</li>
            <li>@Html.ActionLink("All Classes", "Index", "Class")</li>
            <li>@Html.ActionLink("My Students", "GetStudents", "Teacher")</li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li style="padding: 15px; color: white">@Request.Cookies["userEmailCookie"].Value (@Request.Cookies["Role"].Value)</li>
            <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
            <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
        </ul>
    </div>*@

Project2-BuellerWebSln/Bueller.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bueller", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("My Classes", "MyClasses", "Class")</li>
                    <li>@Html.ActionLink("All Classes", "Index", "Class")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>